//DASHBOARD CLICK EVENT
export const CLICK_DASHBOARD_VISITE = 'CLICK_DASHBOARD_VISITE';
export const CLICK_DASHBOARD_MESSAGE = 'CLICK_DASHBOARD_MESSAGE';
export const CLICK_DASHBOARD_APPEL = 'CLICK_DASHBOARD_APPEL';
export const CLICK_DASHBOARD_DEMANDE = 'CLICK_DASHBOARD_DEMANDE';

//NAVIGATION TYPE (WITH BACK BUTTON OR MENU BUTTON)
export const NAVIGATION_TYPE_BACK = 'NAVIGATION_TYPE_BACK';
export const NAVIGATION_TYPE_MENU = 'NAVIGATION_TYPE_MENU';