export const CLICK_DASHBOARD_VISITE = 'CLICK_DASHBOARD_VISITE';
export const CLICK_DASHBOARD_MESSAGE = 'CLICK_DASHBOARD_MESSAGE';
export const CLICK_DASHBOARD_APPEL = 'CLICK_DASHBOARD_APPEL';
export const CLICK_DASHBOARD_DEMANDE = 'CLICK_DASHBOARD_DEMANDE';