export const FETCH_DEMANDES = 'FETCH_DEMANDES'
export const FETCH_DEMANDES_FAILURE = 'FETCH_DEMANDES_FAILURE'
export const FETCH_DEMANDES_SUCCESS = 'FETCH_DEMANDES_SUCCESS'
export const DELETE_DEMANDE = 'DELETE_DEMANDE'
export const DELETE_DEMANDE_FAILURE = 'DELETE_DEMANDE_FAILURE'
export const DELETE_DEMANDE_SUCCESS = 'DELETE_DEMANDE_SUCCESS'

//Create demand
export const CREATE_DEMAND = 'CREATE_DEMAND'
export const CREATE_DEMAND_FAILURE = 'CREATE_DEMAND_FAILURE'
export const CREATE_DEMAND_SUCCESS = 'CREATE_DEMAND_SUCCESS'
export const CREATE_DEMAND_RESET = 'CREATE_DEMAND_RESET'

//Update demand
export const UPDATE_DEMAND = 'UPDATE_DEMAND'
export const UPDATE_DEMAND_FAILURE = 'UPDATE_DEMAND_FAILURE'
export const UPDATE_DEMAND_SUCCESS = 'UPDATE_DEMAND_SUCCESS'
export const UPDATE_DEMAND_RESET = 'UPDATE_DEMAND_RESET'

//Change statut 
export const CHANGE_STATUS_DEMANDE = 'CHANGE_STATUS_DEMANDE'
export const CHANGE_STATUS_DEMANDE_SUCCESS = 'CHANGE_STATUS_DEMANDE_SUCCESS'
export const CHANGE_STATUS_DEMANDE_FAILURE = 'CHANGE_STATUS_DEMANDE_FAILURE'

//Change priorite
export const CHANGE_PRIORITE_DEMANDE = 'CHANGE_PRIORITE_DEMANDE'
export const CHANGE_PRIORITE_DEMANDE_SUCCESS = 'CHANGE_PRIORITE_DEMANDE_SUCCESS'
export const CHANGE_PRIORITE_DEMANDE_FAILURE = 'CHANGE_PRIORITE_DEMANDE_FAILURE'

export const CHANGE_CURRENT_DEMANDE = 'CHANGE_CURRENT_DEMANDE'

//Get detail
export const FETCH_DEMANDE_DETAIL = 'FETCH_DEMANDE_DETAIL'
export const FETCH_DEMANDE_DETAIL_FAILURE = 'FETCH_DEMANDE_DETAIL_FAILURE'
export const FETCH_DEMANDE_DETAIL_SUCCESS = 'FETCH_DEMANDE_DETAIL_SUCCESS'
export const FETCH_DEMANDE_DETAIL_RESET = 'FETCH_DEMANDE_DETAIL_RESET'

//Remove attachments
export const DELETE_ATTACHMENT = 'DELETE_ATTACHMENT'
export const DELETE_ATTACHMENT_FAILURE = 'DELETE_ATTACHMENT_FAILURE'
export const DELETE_ATTACHMENT_SUCCESS = 'DELETE_ATTACHMENT_SUCCESS'
export const DELETE_ATTACHMENT_RESET = 'DELETE_ATTACHMENT_RESET'

//Filter demand
export const CRITERIA_DEMAND = 'CRITERIA_DEMAND'
export const CRITERIA_DEMAND_FAILURE = 'CRITERIA_DEMAND_FAILURE'
export const CRITERIA_DEMAND_SUCCESS = 'CRITERIA_DEMAND_SUCCESS'
export const CRITERIA_DEMAND_FILTER = 'CRITERIA_DEMAND_FILTER'
