export const FETCHING_LOGIN = 'FETCHING_LOGIN'
export const FETCHING_LOGIN_SUCCESS = 'FETCHING_LOGIN_SUCCESS'
export const FETCHING_LOGIN_FAILURE = 'FETCHING_LOGIN_FAILURE'
export const DELETE_USER = 'DELETE_USER'
