# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'Visiorank' do
    pod 'SwiftyJSON', '3.1.4'
    pod 'Charts', '3.0.3'
    pod 'GoogleMaps'
end
post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
    end
end

